export const MATCH_STATUS_END_OF_EVENT = "END_OF_EVENT";
export const MATCH_STATUS_PAUSED = "PAUSED";
export const MATCH_STATUS_STARTED = "STARTED";

export const MATCH_TYPE_NO_TIME = "NO_TIME";
export const MATCH_TYPE_REGULAR = "REGULAR";
export const MATCH_TYPE_REVERSE = "REVERSE";
