export const SPORT_TREE_COUNT_TYPE_EVENT = "EVENT";
export const SPORT_TREE_COUNT_TYPE_MARKET = "MARKET";

export const MENU_ITEM_TYPE_INTERNAL_LINK = "INTERNAL_LINK";
export const MENU_ITEM_TYPE_INTERNAL_NAMED_COMPONENT = "INTERNAL_NAMED_COMPONENT";
export const MENU_ITEM_TYPE_EXTERNAL_LINK = "EXTERNAL_LINK";

export const INTERNAL_NAMED_COMPONENT_TYPE_BETRADAR_VIRTUAL_SPORTS = "BETRADAR_VIRTUAL_SPORTS";
export const INTERNAL_NAMED_COMPONENT_TYPE_BET_CALCULATOR = "BET_CALCULATOR";
export const INTERNAL_NAMED_COMPONENT_TYPE_HOME = "HOME";
export const INTERNAL_NAMED_COMPONENT_TYPE_KIRON_VIRTUAL_SPORTS = "KIRON_VIRTUAL_SPORTS";
export const INTERNAL_NAMED_COMPONENT_TYPE_JACKPOTS = "JACKPOTS";
export const INTERNAL_NAMED_COMPONENT_TYPE_LIVE = "LIVE";
export const INTERNAL_NAMED_COMPONENT_TYPE_LIVE_CALENDAR = "LIVE_CALENDAR";
export const INTERNAL_NAMED_COMPONENT_TYPE_PAGE_CONTENT = "PAGE_CONTENT";
export const INTERNAL_NAMED_COMPONENT_TYPE_PREMATCH = "PREMATCH";
export const INTERNAL_NAMED_COMPONENT_TYPE_RESULTS = "RESULTS";
export const INTERNAL_NAMED_COMPONENT_TYPE_SOLID_GAMING = "SOLID_GAMING";
export const INTERNAL_NAMED_COMPONENT_TYPE_PROMOTIONS = "PROMOTIONS";
