export const TRANSACTION_TYPE_SETTLED = "SETTLED";
export const TRANSACTION_TYPE_PENDING = "PENDING";

export const TRANSACTION_TYPE_BONUS = "BONUS";
export const TRANSACTION_TYPE_OTHER = "OTHER";
export const TRANSACTION_TYPE_PAYMENT = "PAYMENT";

export const TRANSACTION_ITEM_TYPE_CASINO = "CASINO_BET";
export const TRANSACTION_ITEM_TYPE_ADJUSTMENT = "ADJUSTMENT";
export const TRANSACTION_ITEM_TYPE_BONUS = "BONUS";
export const TRANSACTION_ITEM_TYPE_DEPOSIT = "DEPOSIT";
export const TRANSACTION_ITEM_TYPE_WITHDRAWAL = "WITHDRAWAL";
