export const PANEL_ACCOUNT = "PANEL_ACCOUNT";
export const PANEL_CHAT = "PANEL_CHAT";
export const PANEL_BETSLIP = "PANEL_BETSLIP";
export const PANEL_GAME_CENTER = "PANEL_GAME_CENTER";
export const PANEL_SPORTS_TREE = "PANEL_SPORTS_TREE";
